baseURL = "https://rpkgdev-mechanics.netlify.app/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Package Development: the Mechanics"
enableEmoji = true
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Package Development: the Mechanics"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/ropensci-training/2023-pkg-dev-mechanics"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-fw fa-copy'></i> Snippets"
url = "/snippets"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/ropensci-training/2023-pkg-dev-mechanics/edit/main/content/"
  description = "Package Development: the Mechanics"
  author = "Maëlle Salmon"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.reveal_hugo]
theme = "white"
load_default_plugins = false
plugins = [
  "reveal-js/plugin/zoom-js/zoom.js",
  "reveal-js/plugin/notes/notes.js",
]
